name: gcp function keep alive

on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  build:
    name: keep alive
    runs-on: ubuntu-latest
    steps:
      - run: curl -X GET "https://asia-southeast2-muslim-board-ind-1472876095243.cloudfunctions.net/muslimboard-api?v=v2.6.0&op=ping"
